# Generated by Django 5.2.5 on 2025-08-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smtp_host',
            field=models.CharField(default='smtp-mail.outlook.com', help_text='Servidor SMTP', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Senha do e-mail SMTP (use senha de app para Outlook/Hotmail)', max_length=255, null=True),
        ),
    ]
