# Generated by Django 5.2.5 on 2025-08-07 05:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_line', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ready Line')),
                ('vip_line', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VIP Line')),
                ('overflow_kiosk', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Overflow Kiosk')),
                ('overflow_2', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Overflow 2')),
                ('black_top', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Black Top')),
                ('return_line', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Return Line')),
                ('mecanico', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mecânico')),
                ('gas_run', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gas Run')),
                ('total_cleaned', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Carros Limpos')),
                ('forecasted_drops', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Previsão de Drops')),
                ('enviar_por_email', models.BooleanField(default=False, verbose_name='Enviar por e-mail')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='E-mail enviado')),
                ('tentativas_envio', models.PositiveIntegerField(default=0, verbose_name='Tentativas de envio')),
                ('erro_envio', models.TextField(blank=True, null=True, verbose_name='Erro no envio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='relatorios/%Y/%m/%d/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do upload')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='reports.relatorio', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Imagem do Relatório',
                'verbose_name_plural': 'Imagens dos Relatórios',
                'ordering': ['data_upload'],
            },
        ),
    ]
