# Generated by Django 5.2.5 on 2025-08-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='unidade_empresa',
            field=models.CharField(blank=True, help_text='Nome da unidade ou empresa', max_length=200, verbose_name='Unidade/Empresa'),
        ),
    ]
