# Generated by Django 5.2.5 on 2025-08-07 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_relatorio_unidade_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_line', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ready Line')),
                ('vip_line', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VIP Line')),
                ('overflow_kiosk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Overflow Kiosk')),
                ('overflow_2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Overflow 2')),
                ('black_top', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Black Top')),
                ('return_line', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Return Line')),
                ('mecanico', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mecânico')),
                ('gas_run', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gas Run')),
                ('total_cleaned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Cleaned')),
                ('forecasted_drops', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Forecasted Drops')),
                ('send_email', models.BooleanField(default=False, verbose_name='Enviar por E-mail')),
                ('email_status', models.CharField(choices=[('sent', 'Enviado'), ('not_sent', 'Não Enviado'), ('error', 'Erro no Envio')], default='not_sent', max_length=20, verbose_name='Status do E-mail')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ImagemRelatorio',
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
